title: RaduTek's Devices
email: me@radutek.uk
description: This website contains information about the devices in my collection.

collections:
    devices:
        output: true
        permalink: /:path/
